name: Manual
on:
  issue_comment:
    types: [created, edited]

jobs:
  update-benchmarks:
    # if: ${{ github.event.issue.pull_request && contains(['COLLABORATOR', 'MEMBER', 'OWNER'], github.event.issue.author_association) && startsWith(github.event.issue.comment.body, "/update_benchmarks"}}
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make Changes
        run: |
          echo "a testing change" >> testing.txt

      - name: Commit Changes
        run: |
          echo "github.event.issue.pull_request.head.ref ${{ github.event.issue.pull_request.head.ref }}"
          echo "event.comment.body ${{ event.comment.body }}
          echo "event.comment.issue_url ${{ event.comment.issue_url }}
          echo "event.comment.id ${{ event.comment.id }}
          echo "event.comment.url ${{ event.comment.url }}
          echo "event.issue.comment.body ${{ event.issue.comment.body }}
          echo "event.issue.html_url ${{ event.issue.html_url }}
          echo "event.issue.id ${{ event.issue.id }}
          echo "event.issue.number ${{ event.issue.number }}
          echo "event.issue.pull_request.url ${{ event.issue.pull_request.url }}
          echo "event.issue.pull_request.html_url ${{ event.issue.pull_request.html_url }}
          echo "event.issue.repository_url ${{ event.issue.repository_url }}
          echo "event.issue.url ${{ event.issue.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.issue.pull_request.head.ref }}
