name: Manual
on:
  issue_comment:
    types: [created, edited]

jobs:
  benchmarks:
    name: Update Benchmarks
    uses: ./.github/workflows/benchmarks_update.yml
    with:
      benchmark_package_path: "Benchmarks"
